// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylamlwwvcpvjyeqmvtrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYW1sd3d2Y3B2anllcW12dHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTQxMTcsImV4cCI6MjA2MjI5MDExN30.1pGtsCCPxxiGQcjQdept40J-Bc1QdI1A3AYObe2AP-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);